# ----------------------------------------------------
# INTERNAL CONNECTOR CONFIGURATION
# For Connector Developer use only
# ----------------------------------------------------

solace:
  connector:
    workflows:
      0:
        input-bindings:
          - input-0
        output-bindings:
          - output-0
      1:
        input-bindings:
          - input-1
        output-bindings:
          - output-1
      2:
        input-bindings:
          - input-2
        output-bindings:
          - output-2
      3:
        input-bindings:
          - input-3
        output-bindings:
          - output-3
      4:
        input-bindings:
          - input-4
        output-bindings:
          - output-4
      5:
        input-bindings:
          - input-5
        output-bindings:
          - output-5
      6:
        input-bindings:
          - input-6
        output-bindings:
          - output-6
      7:
        input-bindings:
          - input-7
        output-bindings:
          - output-7
      8:
        input-bindings:
          - input-8
        output-bindings:
          - output-8
      9:
        input-bindings:
          - input-9
        output-bindings:
          - output-9
      10:
        input-bindings:
          - input-10
        output-bindings:
          - output-10
      11:
        input-bindings:
          - input-11
        output-bindings:
          - output-11
      12:
        input-bindings:
          - input-12
        output-bindings:
          - output-12
      13:
        input-bindings:
          - input-13
        output-bindings:
          - output-13
      14:
        input-bindings:
          - input-14
        output-bindings:
          - output-14
      15:
        input-bindings:
          - input-15
        output-bindings:
          - output-15
      16:
        input-bindings:
          - input-16
        output-bindings:
          - output-16
      17:
        input-bindings:
          - input-17
        output-bindings:
          - output-17
      18:
        input-bindings:
          - input-18
        output-bindings:
          - output-18
      19:
        input-bindings:
          - input-19
        output-bindings:
          - output-19
